
# Node.js

# Build a general Node.js project with npm.

# Add steps that analyze code, save build artifacts, deploy, and more:

# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript



trigger:

- master



jobs: 

- job:

  pool:

    vmImage: 'ubuntu-latest'



  steps:

  - task: NodeTool@0

    inputs:

      versionSpec: '12.x'

    displayName: 'Install Node.js'



  - script: |

      npm install

      npm install - g serverless

      npm install -D https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz

    displayName: 'npm install and serverless install'

  - task: DockerInstaller@0

    inputs:

      dockerVersion: '17.09.0-ce'

    displayName: 'Install Docker'



  - task: AWSShellScript@1

    inputs:

        awsCredentials: 'rolandop-cp'

        regionName: $(AWS_REGION)

        scriptType: 'inline'

        inlineScript: 

          ./node_modules/.bin/serverless package -t $(CLOUDGUARD_TOKEN)

    displayName: 'Run Serverless package'



  - task: PublishPipelineArtifact@1

    inputs:

      targetPath: '$(System.DefaultWorkingDirectory)/cloudguard_output'

      artifact: 'cloudguard_output'

      publishLocation: 'pipeline'

    displayName: 'Publishing Artifacts'